
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - devops.codepy.net
  resources:
  - statics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.codepy.net
  resources:
  - statics/finalizers
  verbs:
  - update
- apiGroups:
  - devops.codepy.net
  resources:
  - statics/status
  verbs:
  - get
  - patch
  - update
