# permissions for end users to edit statics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: static-editor-role
rules:
- apiGroups:
  - devops.codepy.net
  resources:
  - statics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.codepy.net
  resources:
  - statics/status
  verbs:
  - get
